version: 2
updates:
    # Check for nuget package updates.
  - package-ecosystem: "nuget" 
    directory: "/Secure-Web-App/"
    schedule:
      interval: "weekly"

    # Check for github-action version updates.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
