# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Secure-Web-App
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Secure-Web-App
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Secure-Web-App
      
    - name: Run SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
      with:
        args: >
          -Dsonar.projectKey=Cyber-Security-S7_Secure-Web-App
          -Dsonar.organization=cyber-security-s7
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.inclusions=**/*.cs
          -Dsonar.exclusions=**/*.json
