name: OWASP ZAP Scan Full

on:
  workflow_dispatch:

jobs:
  setup_docker:
    runs-on: ubuntu-latest
    name: Set up Docker container and run zap scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker
        run: |
          docker pull lukas100/secure-web-application:latest
          docker run -d -p 8080:8080 lukas100/secure-web-application:latest

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.PAT }}
          target: 'http://localhost:80'
